### ISSUE TITLE
serialの書き込みエラーの発生

### ISSUE THREAD

**Issue by 9511batayan** [bata-kawa3/roboclaw#1]
roboclawのバージョンを最新にし、USBコントロール使用しようとしたらエラーを吐いてしまった。
Windowsでは正常に動き、Linuxでは失敗してしまった。
実行コマンド
sudo python key_roboclaw.py
sudo python3 key_roboclaw.py
結果
"SerialException: write failed: [Errno 5] Input/output error".

**Comment by 9511batayan** [comment]
1台はLinuxでの動作を確認できた。
もう一台はアップデート、アップグレードをした後だが、以前と変わらず

**Comment by 9511batayan** [comment]
Traceback (most recent call last):
  File "roboclaw_speeddistance.py", line 57, in <module>
    buffers = rc.ReadBuffers(address);
  File "/home/nsr01/shiba/roboclaw.py", line 809, in ReadBuffers
    val = self._read2(address,self.Cmd.GETBUFFERS)
  File "/home/nsr01/shiba/roboclaw.py", line 219, in _read2
    val1 = self._readword()
  File "/home/nsr01/shiba/roboclaw.py", line 147, in _readword
    val1 = self._readbyte()
  File "/home/nsr01/shiba/roboclaw.py", line 139, in _readbyte
    data = self._port.read(1)
roboclaw_speeddistance.py is run
 
 File "/usr/lib/python2.7/dist-packages/serial/serialposix.py", line 495, in read
    raise SerialException('device reports readiness to read but returned no data (device disconnected or multiple access on port?)')
serial.serialutil.SerialException: device reports readiness to read but returned no data (device disconnected or multiple access on port?)

**Comment by 9511batayan** [comment]
QPPSを最大値以上に書き込むと発生したことが分かった
